-- Countries

INSERT INTO Country_Code (country_code, country_name) values ('AF', 'Afghanistan');
INSERT INTO Country_Code (country_code, country_name) values ('AL', 'Albania');
INSERT INTO Country_Code (country_code, country_name) values ('DZ', 'Algeria');
INSERT INTO Country_Code (country_code, country_name) values ('AS', 'American Samoa');
INSERT INTO Country_Code (country_code, country_name) values ('AD', 'Andorra');
INSERT INTO Country_Code (country_code, country_name) values ('AO', 'Angola');
INSERT INTO Country_Code (country_code, country_name) values ('AI', 'Anguilla');
INSERT INTO Country_Code (country_code, country_name) values ('AQ', 'Antarctica');
INSERT INTO Country_Code (country_code, country_name) values ('AG', 'Antigua & Barbuda');
INSERT INTO Country_Code (country_code, country_name) values ('SA', 'Arabia, Saudi');
INSERT INTO Country_Code (country_code, country_name) values ('AR', 'Argentina');
INSERT INTO Country_Code (country_code, country_name) values ('AM', 'Armenia');
INSERT INTO Country_Code (country_code, country_name) values ('AW', 'Aruba');
INSERT INTO Country_Code (country_code, country_name) values ('AU', 'Australia');
INSERT INTO Country_Code (country_code, country_name) values ('AT', 'Austria');
INSERT INTO Country_Code (country_code, country_name) values ('AZ', 'Azerbaijan');
INSERT INTO Country_Code (country_code, country_name) values ('BS', 'Bahamas, The');
INSERT INTO Country_Code (country_code, country_name) values ('BH', 'Bahrain');
INSERT INTO Country_Code (country_code, country_name) values ('BD', 'Bangladesh');
INSERT INTO Country_Code (country_code, country_name) values ('BB', 'Barbados');
INSERT INTO Country_Code (country_code, country_name) values ('BY', 'Belarus');
INSERT INTO Country_Code (country_code, country_name) values ('BE', 'Belgium');
INSERT INTO Country_Code (country_code, country_name) values ('BZ', 'Belize');
INSERT INTO Country_Code (country_code, country_name) values ('BJ', 'Benin');
INSERT INTO Country_Code (country_code, country_name) values ('BM', 'Bermuda');
INSERT INTO Country_Code (country_code, country_name) values ('BT', 'Bhutan');
INSERT INTO Country_Code (country_code, country_name) values ('BO', 'Bolivia');
INSERT INTO Country_Code (country_code, country_name) values ('BQ', 'Bonaire, St.Eustat, Saba');
INSERT INTO Country_Code (country_code, country_name) values ('BA', 'Bosnia and Herzegovina');
INSERT INTO Country_Code (country_code, country_name) values ('BW', 'Botswana');
INSERT INTO Country_Code (country_code, country_name) values ('BV', 'Bouvet Island');
INSERT INTO Country_Code (country_code, country_name) values ('BR', 'Brazil');
INSERT INTO Country_Code (country_code, country_name) values ('IO', 'British Indian Ocean T.');
INSERT INTO Country_Code (country_code, country_name) values ('BN', 'Brunei Darussalam');
INSERT INTO Country_Code (country_code, country_name) values ('BG', 'Bulgaria');
INSERT INTO Country_Code (country_code, country_name) values ('BF', 'Burkina Faso');
INSERT INTO Country_Code (country_code, country_name) values ('BI', 'Burundi');
INSERT INTO Country_Code (country_code, country_name) values ('KH', 'Cambodia');
INSERT INTO Country_Code (country_code, country_name) values ('CM', 'Cameroon');
INSERT INTO Country_Code (country_code, country_name) values ('CA', 'Canada');
INSERT INTO Country_Code (country_code, country_name) values ('CV', 'Cape Verde');
INSERT INTO Country_Code (country_code, country_name) values ('KY', 'Cayman Islands');
INSERT INTO Country_Code (country_code, country_name) values ('CF', 'Central African Republic');
INSERT INTO Country_Code (country_code, country_name) values ('TD', 'Chad');
INSERT INTO Country_Code (country_code, country_name) values ('CL', 'Chile');
INSERT INTO Country_Code (country_code, country_name) values ('CN', 'China');
INSERT INTO Country_Code (country_code, country_name) values ('CX', 'Christmas Island');
INSERT INTO Country_Code (country_code, country_name) values ('CC', 'Cocos (Keeling) Islands');
INSERT INTO Country_Code (country_code, country_name) values ('CO', 'Colombia');
INSERT INTO Country_Code (country_code, country_name) values ('KM', 'Comoros');
INSERT INTO Country_Code (country_code, country_name) values ('CG', 'Congo');
INSERT INTO Country_Code (country_code, country_name) values ('CD', 'Congo, Dem. Rep. of the');
INSERT INTO Country_Code (country_code, country_name) values ('CK', 'Cook Islands');
INSERT INTO Country_Code (country_code, country_name) values ('CR', 'Costa Rica');
INSERT INTO Country_Code (country_code, country_name) values ('CI', 'Cote D''Ivoire');
INSERT INTO Country_Code (country_code, country_name) values ('HR', 'Croatia');
INSERT INTO Country_Code (country_code, country_name) values ('CU', 'Cuba');
INSERT INTO Country_Code (country_code, country_name) values ('CY', 'Cyprus');
INSERT INTO Country_Code (country_code, country_name) values ('CZ', 'Czech Republic');
INSERT INTO Country_Code (country_code, country_name) values ('DK', 'Denmark');
INSERT INTO Country_Code (country_code, country_name) values ('DJ', 'Djibouti');
INSERT INTO Country_Code (country_code, country_name) values ('DM', 'Dominica');
INSERT INTO Country_Code (country_code, country_name) values ('DO', 'Dominican Republic');
INSERT INTO Country_Code (country_code, country_name) values ('TP', 'East Timor (Timor-Leste)');
INSERT INTO Country_Code (country_code, country_name) values ('EC', 'Ecuador');
INSERT INTO Country_Code (country_code, country_name) values ('EG', 'Egypt');
INSERT INTO Country_Code (country_code, country_name) values ('SV', 'El Salvador');
INSERT INTO Country_Code (country_code, country_name) values ('GQ', 'Equatorial Guinea');
INSERT INTO Country_Code (country_code, country_name) values ('ER', 'Eritrea');
INSERT INTO Country_Code (country_code, country_name) values ('EE', 'Estonia');
INSERT INTO Country_Code (country_code, country_name) values ('ET', 'Ethiopia');
INSERT INTO Country_Code (country_code, country_name) values ('EU', 'European Union');
INSERT INTO Country_Code (country_code, country_name) values ('FK', 'Falkland Islands (Malvinas)');
INSERT INTO Country_Code (country_code, country_name) values ('FO', 'Faroe Islands');
INSERT INTO Country_Code (country_code, country_name) values ('FJ', 'Fiji');
INSERT INTO Country_Code (country_code, country_name) values ('FI', 'Finland');
INSERT INTO Country_Code (country_code, country_name) values ('FR', 'France');
INSERT INTO Country_Code (country_code, country_name) values ('GF', 'French Guiana');
INSERT INTO Country_Code (country_code, country_name) values ('PF', 'French Polynesia');
INSERT INTO Country_Code (country_code, country_name) values ('TF', 'French Southern Terr.');
INSERT INTO Country_Code (country_code, country_name) values ('GA', 'Gabon');
INSERT INTO Country_Code (country_code, country_name) values ('GM', 'Gambia, the');
INSERT INTO Country_Code (country_code, country_name) values ('GE', 'Georgia');
INSERT INTO Country_Code (country_code, country_name) values ('DE', 'Germany');
INSERT INTO Country_Code (country_code, country_name) values ('GH', 'Ghana');
INSERT INTO Country_Code (country_code, country_name) values ('GI', 'Gibraltar');
INSERT INTO Country_Code (country_code, country_name) values ('GR', 'Greece');
INSERT INTO Country_Code (country_code, country_name) values ('GL', 'Greenland');
INSERT INTO Country_Code (country_code, country_name) values ('GD', 'Grenada');
INSERT INTO Country_Code (country_code, country_name) values ('GU', 'Guam');
INSERT INTO Country_Code (country_code, country_name) values ('GT', 'Guatemala');
INSERT INTO Country_Code (country_code, country_name) values ('GG', 'Guernsey and Alderney');
INSERT INTO Country_Code (country_code, country_name) values ('GN', 'Guinea');
INSERT INTO Country_Code (country_code, country_name) values ('GW', 'Guinea-Bissau');
INSERT INTO Country_Code (country_code, country_name) values ('GP', 'Guinea, Equatorial');
INSERT INTO Country_Code (country_code, country_name) values ('GY', 'Guyana');
INSERT INTO Country_Code (country_code, country_name) values ('HT', 'Haiti');
INSERT INTO Country_Code (country_code, country_name) values ('HM', 'Heard & McDonald Is.(AU)');
INSERT INTO Country_Code (country_code, country_name) values ('VA', 'Holy See (Vatican)');
INSERT INTO Country_Code (country_code, country_name) values ('HN', 'Honduras');
INSERT INTO Country_Code (country_code, country_name) values ('HK', 'Hong Kong, (China)');
INSERT INTO Country_Code (country_code, country_name) values ('HU', 'Hungary');
INSERT INTO Country_Code (country_code, country_name) values ('IS', 'Iceland');
INSERT INTO Country_Code (country_code, country_name) values ('IN', 'India');
INSERT INTO Country_Code (country_code, country_name) values ('ID', 'Indonesia');
INSERT INTO Country_Code (country_code, country_name) values ('IR', 'Iran, Islamic Republic of');
INSERT INTO Country_Code (country_code, country_name) values ('IQ', 'Iraq');
INSERT INTO Country_Code (country_code, country_name) values ('IE', 'Ireland');
INSERT INTO Country_Code (country_code, country_name) values ('IL', 'Israel');
INSERT INTO Country_Code (country_code, country_name) values ('IT', 'Italy');
INSERT INTO Country_Code (country_code, country_name) values ('JM', 'Jamaica');
INSERT INTO Country_Code (country_code, country_name) values ('JP', 'Japan');
INSERT INTO Country_Code (country_code, country_name) values ('JE', 'Jersey');
INSERT INTO Country_Code (country_code, country_name) values ('JO', 'Jordan');
INSERT INTO Country_Code (country_code, country_name) values ('KZ', 'Kazakhstan');
INSERT INTO Country_Code (country_code, country_name) values ('KE', 'Kenya');
INSERT INTO Country_Code (country_code, country_name) values ('KI', 'Kiribati');
INSERT INTO Country_Code (country_code, country_name) values ('KR', 'Korea, (South) Republic of');
INSERT INTO Country_Code (country_code, country_name) values ('KV', 'Kosovo');
INSERT INTO Country_Code (country_code, country_name) values ('KW', 'Kuwait');
INSERT INTO Country_Code (country_code, country_name) values ('KG', 'Kyrgyzstan');
INSERT INTO Country_Code (country_code, country_name) values ('LV', 'Latvia');
INSERT INTO Country_Code (country_code, country_name) values ('LB', 'Lebanon');
INSERT INTO Country_Code (country_code, country_name) values ('LS', 'Lesotho');
INSERT INTO Country_Code (country_code, country_name) values ('LR', 'Liberia');
INSERT INTO Country_Code (country_code, country_name) values ('LY', 'Libyan Arab Jamahiriya');
INSERT INTO Country_Code (country_code, country_name) values ('LI', 'Liechtenstein');
INSERT INTO Country_Code (country_code, country_name) values ('LT', 'Lithuania');
INSERT INTO Country_Code (country_code, country_name) values ('LU', 'Luxembourg');
INSERT INTO Country_Code (country_code, country_name) values ('MO', 'Macao, (China)');
INSERT INTO Country_Code (country_code, country_name) values ('MK', 'Macedonia, TFYR');
INSERT INTO Country_Code (country_code, country_name) values ('MG', 'Madagascar');
INSERT INTO Country_Code (country_code, country_name) values ('MW', 'Malawi');
INSERT INTO Country_Code (country_code, country_name) values ('MY', 'Malaysia');
INSERT INTO Country_Code (country_code, country_name) values ('MV', 'Maldives');
INSERT INTO Country_Code (country_code, country_name) values ('ML', 'Mali');
INSERT INTO Country_Code (country_code, country_name) values ('MT', 'Malta');
INSERT INTO Country_Code (country_code, country_name) values ('IM', 'Man, Isle of');
INSERT INTO Country_Code (country_code, country_name) values ('MH', 'Marshall Islands');
INSERT INTO Country_Code (country_code, country_name) values ('MQ', 'Martinique (FR)');
INSERT INTO Country_Code (country_code, country_name) values ('MR', 'Mauritania');
INSERT INTO Country_Code (country_code, country_name) values ('MU', 'Mauritius');
INSERT INTO Country_Code (country_code, country_name) values ('YT', 'Mayotte (FR)');
INSERT INTO Country_Code (country_code, country_name) values ('MX', 'Mexico');
INSERT INTO Country_Code (country_code, country_name) values ('FM', 'Micronesia, Fed. States of');
INSERT INTO Country_Code (country_code, country_name) values ('MD', 'Moldova, Republic of');
INSERT INTO Country_Code (country_code, country_name) values ('MC', 'Monaco');
INSERT INTO Country_Code (country_code, country_name) values ('MN', 'Mongolia');
INSERT INTO Country_Code (country_code, country_name) values ('CS', 'Montenegro');
INSERT INTO Country_Code (country_code, country_name) values ('MS', 'Montserrat');
INSERT INTO Country_Code (country_code, country_name) values ('MA', 'Morocco');
INSERT INTO Country_Code (country_code, country_name) values ('MZ', 'Mozambique');
INSERT INTO Country_Code (country_code, country_name) values ('MM', 'Myanmar (ex-Burma)');
INSERT INTO Country_Code (country_code, country_name) values ('NA', 'Namibia');
INSERT INTO Country_Code (country_code, country_name) values ('NR', 'Nauru');
INSERT INTO Country_Code (country_code, country_name) values ('NP', 'Nepal');
INSERT INTO Country_Code (country_code, country_name) values ('NL', 'Netherlands');
INSERT INTO Country_Code (country_code, country_name) values ('AN', 'Netherlands Antilles');
INSERT INTO Country_Code (country_code, country_name) values ('NC', 'New Caledonia');
INSERT INTO Country_Code (country_code, country_name) values ('NZ', 'New Zealand');
INSERT INTO Country_Code (country_code, country_name) values ('NI', 'Nicaragua');
INSERT INTO Country_Code (country_code, country_name) values ('NE', 'Niger');
INSERT INTO Country_Code (country_code, country_name) values ('NG', 'Nigeria');
INSERT INTO Country_Code (country_code, country_name) values ('NU', 'Niue');
INSERT INTO Country_Code (country_code, country_name) values ('NF', 'Norfolk Island');
INSERT INTO Country_Code (country_code, country_name) values ('MP', 'Northern Mariana Islands');
INSERT INTO Country_Code (country_code, country_name) values ('NO', 'Norway');
INSERT INTO Country_Code (country_code, country_name) values ('OM', 'Oman');
INSERT INTO Country_Code (country_code, country_name) values ('PK', 'Pakistan');
INSERT INTO Country_Code (country_code, country_name) values ('PW', 'Palau');
INSERT INTO Country_Code (country_code, country_name) values ('PS', 'Palestinian Territory');
INSERT INTO Country_Code (country_code, country_name) values ('PA', 'Panama');
INSERT INTO Country_Code (country_code, country_name) values ('PG', 'Papua New Guinea');
INSERT INTO Country_Code (country_code, country_name) values ('PY', 'Paraguay');
INSERT INTO Country_Code (country_code, country_name) values ('PE', 'Peru');
INSERT INTO Country_Code (country_code, country_name) values ('PH', 'Philippines');
INSERT INTO Country_Code (country_code, country_name) values ('PN', 'Pitcairn Island');
INSERT INTO Country_Code (country_code, country_name) values ('PL', 'Poland');
INSERT INTO Country_Code (country_code, country_name) values ('PT', 'Portugal');
INSERT INTO Country_Code (country_code, country_name) values ('PR', 'Puerto Rico');
INSERT INTO Country_Code (country_code, country_name) values ('QA', 'Qatar');
INSERT INTO Country_Code (country_code, country_name) values ('RE', 'Reunion (FR)');
INSERT INTO Country_Code (country_code, country_name) values ('RO', 'Romania');
INSERT INTO Country_Code (country_code, country_name) values ('RU', 'Russia (Russian Fed.)');
INSERT INTO Country_Code (country_code, country_name) values ('RW', 'Rwanda');
INSERT INTO Country_Code (country_code, country_name) values ('EH', 'Sahara, Western');
INSERT INTO Country_Code (country_code, country_name) values ('BL', 'Saint Barthelemy (FR)');
INSERT INTO Country_Code (country_code, country_name) values ('SH', 'Saint Helena (UK)');
INSERT INTO Country_Code (country_code, country_name) values ('KN', 'Saint Kitts and Nevis');
INSERT INTO Country_Code (country_code, country_name) values ('LC', 'Saint Lucia');
INSERT INTO Country_Code (country_code, country_name) values ('MF', 'Saint Martin (FR)');
INSERT INTO Country_Code (country_code, country_name) values ('PM', 'S Pierre & Miquelon(FR)');
INSERT INTO Country_Code (country_code, country_name) values ('VC', 'S Vincent & Grenadines');
INSERT INTO Country_Code (country_code, country_name) values ('WS', 'Samoa');
INSERT INTO Country_Code (country_code, country_name) values ('SM', 'San Marino');
INSERT INTO Country_Code (country_code, country_name) values ('ST', 'Sao Tome and Principe');
INSERT INTO Country_Code (country_code, country_name) values ('SN', 'Senegal');
INSERT INTO Country_Code (country_code, country_name) values ('RS', 'Serbia');
INSERT INTO Country_Code (country_code, country_name) values ('SC', 'Seychelles');
INSERT INTO Country_Code (country_code, country_name) values ('SL', 'Sierra Leone');
INSERT INTO Country_Code (country_code, country_name) values ('SG', 'Singapore');
INSERT INTO Country_Code (country_code, country_name) values ('SK', 'Slovakia');
INSERT INTO Country_Code (country_code, country_name) values ('SI', 'Slovenia');
INSERT INTO Country_Code (country_code, country_name) values ('SB', 'Solomon Islands');
INSERT INTO Country_Code (country_code, country_name) values ('SO', 'Somalia');
INSERT INTO Country_Code (country_code, country_name) values ('ZA', 'South Africa');
INSERT INTO Country_Code (country_code, country_name) values ('GS', 'S.George & S.Sandwich');
INSERT INTO Country_Code (country_code, country_name) values ('SS', 'South Sudan');
INSERT INTO Country_Code (country_code, country_name) values ('ES', 'Spain');
INSERT INTO Country_Code (country_code, country_name) values ('LK', 'Sri Lanka (ex-Ceilan)');
INSERT INTO Country_Code (country_code, country_name) values ('SD', 'Sudan');
INSERT INTO Country_Code (country_code, country_name) values ('SR', 'Suriname');
INSERT INTO Country_Code (country_code, country_name) values ('SJ', 'Svalbard & Jan Mayen Is.');
INSERT INTO Country_Code (country_code, country_name) values ('SZ', 'Swaziland');
INSERT INTO Country_Code (country_code, country_name) values ('SE', 'Sweden');
INSERT INTO Country_Code (country_code, country_name) values ('CH', 'Switzerland');
INSERT INTO Country_Code (country_code, country_name) values ('SY', 'Syrian Arab Republic');
INSERT INTO Country_Code (country_code, country_name) values ('TW', 'Taiwan');
INSERT INTO Country_Code (country_code, country_name) values ('TJ', 'Tajikistan');
INSERT INTO Country_Code (country_code, country_name) values ('TZ', 'Tanzania, United Rep. of');
INSERT INTO Country_Code (country_code, country_name) values ('TH', 'Thailand');
INSERT INTO Country_Code (country_code, country_name) values ('TG', 'Togo');
INSERT INTO Country_Code (country_code, country_name) values ('TK', 'Tokelau');
INSERT INTO Country_Code (country_code, country_name) values ('TO', 'Tonga');
INSERT INTO Country_Code (country_code, country_name) values ('TT', 'Trinidad & Tobago');
INSERT INTO Country_Code (country_code, country_name) values ('TN', 'Tunisia');
INSERT INTO Country_Code (country_code, country_name) values ('TR', 'Turkey');
INSERT INTO Country_Code (country_code, country_name) values ('TM', 'Turkmenistan');
INSERT INTO Country_Code (country_code, country_name) values ('TC', 'Turks and Caicos Is.');
INSERT INTO Country_Code (country_code, country_name) values ('TV', 'Tuvalu');
INSERT INTO Country_Code (country_code, country_name) values ('UG', 'Uganda');
INSERT INTO Country_Code (country_code, country_name) values ('UA', 'Ukraine');
INSERT INTO Country_Code (country_code, country_name) values ('AE', 'United Arab Emirates');
INSERT INTO Country_Code (country_code, country_name) values ('UK', 'United Kingdom');
INSERT INTO Country_Code (country_code, country_name) values ('US', 'United States');
INSERT INTO Country_Code (country_code, country_name) values ('UM', 'US Minor Outlying Isl.');
INSERT INTO Country_Code (country_code, country_name) values ('UY', 'Uruguay');
INSERT INTO Country_Code (country_code, country_name) values ('UZ', 'Uzbekistan');
INSERT INTO Country_Code (country_code, country_name) values ('VU', 'Vanuatu');
INSERT INTO Country_Code (country_code, country_name) values ('VE', 'Venezuela');
INSERT INTO Country_Code (country_code, country_name) values ('VN', 'Viet Nam');
INSERT INTO Country_Code (country_code, country_name) values ('VG', 'Virgin Islands, British');
INSERT INTO Country_Code (country_code, country_name) values ('VI', 'Virgin Islands, U.S.');
INSERT INTO Country_Code (country_code, country_name) values ('WF', 'Wallis and Futuna');
INSERT INTO Country_Code (country_code, country_name) values ('YE', 'Yemen');
INSERT INTO Country_Code (country_code, country_name) values ('ZM', 'Zambia');
INSERT INTO Country_Code (country_code, country_name) values ('ZW', 'Zimbabwe');

-- US States
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('AL', 'US', 'Alabama');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('AK', 'US', 'Alaska');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('AZ', 'US', 'Arizona');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('AR', 'US', 'Arkansas');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('CA', 'US', 'California');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('CO', 'US', 'Colorado');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('CT', 'US', 'Connecticut');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('DE', 'US', 'Delaware');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('FL', 'US', 'Florida');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('GA', 'US', 'Georgia');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('HI', 'US', 'Hawaii');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('ID', 'US', 'Idaho');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('IL', 'US', 'Illinois');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('IN', 'US', 'Indiana');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('IA', 'US', 'Iowa');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('KS', 'US', 'Kansas');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('KY', 'US', 'Kentucky');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('LA', 'US', 'Louisiana');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('ME', 'US', 'Maine');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('MD', 'US', 'Maryland');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('MA', 'US', 'Massachusetts');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('MI', 'US', 'Michigan');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('MN', 'US', 'Minnesota');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('MS', 'US', 'Mississippi');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('MO', 'US', 'Missouri');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('MT', 'US', 'Montana');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('NE', 'US', 'Nebraska');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('NV', 'US', 'Nevada');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('NH', 'US', 'New Hampshire');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('NJ', 'US', 'New Jersey');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('NM', 'US', 'New Mexico');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('NY', 'US', 'New York');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('NC', 'US', 'North Carolina');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('ND', 'US', 'North Dakota');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('OH', 'US', 'Ohio');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('OK', 'US', 'Oklahoma');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('OR', 'US', 'Oregon');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('PA', 'US', 'Pennsylvania');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('RI', 'US', 'Rhode Island');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('SC', 'US', 'South Carolina');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('SD', 'US', 'South Dakota');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('TN', 'US', 'Tennessee');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('TX', 'US', 'Texas');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('UT', 'US', 'Utah');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('VT', 'US', 'Vermont');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('VA', 'US', 'Virginia');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('WA', 'US', 'Washington');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('WV', 'US', 'West Virginia');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('WI', 'US', 'Wisconsin');
INSERT INTO Country_Code_State (state_short_name, country_code, state_name) values ('WY', 'US', 'Wyoming');


-- Industries

INSERT INTO Industry_Code(industry_code_id, description) values (11, 'Agriculture, Forestry, Fishing, Hunting');
INSERT INTO Industry_Code(industry_code_id, description) values (21, 'Mining, Quarrying, Oil/Gas Extraction');
INSERT INTO Industry_Code(industry_code_id, description) values (22, 'Utilities');
INSERT INTO Industry_Code(industry_code_id, description) values (23, 'Construction');
INSERT INTO Industry_Code(industry_code_id, description) values (33, 'Manufacturing');
INSERT INTO Industry_Code(industry_code_id, description) values (31, 'Food & Beverage');
INSERT INTO Industry_Code(industry_code_id, description) values (32, 'CPG Consumer Packaged Goods');
INSERT INTO Industry_Code(industry_code_id, description) values (42, 'Wholesale');
INSERT INTO Industry_Code(industry_code_id, description) values (44, 'Retail');
INSERT INTO Industry_Code(industry_code_id, description) values (48, 'Transportation and Warehousing');
INSERT INTO Industry_Code(industry_code_id, description) values (484, 'Carriers');
INSERT INTO Industry_Code(industry_code_id, description) values (4885, '3PL/Third Party Logistics');
INSERT INTO Industry_Code(industry_code_id, description) values (51, 'Information');
INSERT INTO Industry_Code(industry_code_id, description) values (52, 'Finance and Insurance');
INSERT INTO Industry_Code(industry_code_id, description) values (53, 'Real Estate and Rental and Leasing');
INSERT INTO Industry_Code(industry_code_id, description) values (54, 'Professional, Scientific, Technical');
INSERT INTO Industry_Code(industry_code_id, description) values (55, 'Management of Companies/Enterprises');
INSERT INTO Industry_Code(industry_code_id, description) values (56, 'Administrative and Support Services');
INSERT INTO Industry_Code(industry_code_id, description) values (61, 'Educational Services');
INSERT INTO Industry_Code(industry_code_id, description) values (62, 'Health Care and Social Assistance');
INSERT INTO Industry_Code(industry_code_id, description) values (71, 'Arts, Entertainment and Recreation');
INSERT INTO Industry_Code(industry_code_id, description) values (72, 'Accommodation and Food Services');
INSERT INTO Industry_Code(industry_code_id, description) values (81, 'Other Services');
INSERT INTO Industry_Code(industry_code_id, description) values (92, 'Public Administrative (Government)');
INSERT INTO Industry_Code(industry_code_id, description) values (99, 'Nonclassifiable');

-- set all current metrics as not total
update Metric set is_total = false;

-- Asociate all current metrics with the only existing matrix
insert into Matrix_Metric set matrix_id = 1, metric_id = 16;
insert into Matrix_Metric set matrix_id = 1, metric_id = 17;
insert into Matrix_Metric set matrix_id = 1, metric_id = 18;
insert into Matrix_Metric set matrix_id = 1, metric_id = 19;
insert into Matrix_Metric set matrix_id = 1, metric_id = 20;
insert into Matrix_Metric set matrix_id = 1, metric_id = 21;
insert into Matrix_Metric set matrix_id = 1, metric_id = 22;
insert into Matrix_Metric set matrix_id = 1, metric_id = 23;
insert into Matrix_Metric set matrix_id = 1, metric_id = 24;
insert into Matrix_Metric set matrix_id = 1, metric_id = 25;


-- Freight spent by mode: display totals and %
update Metric_Catg set catg_option_type = 3 where metric_catg_id = 1;
-- General Information: regular category
update Metric_Catg set catg_option_type = 1 where metric_catg_id = 2;

-- insert 'total' metric for freigh spent by mode
insert into Metric set metric_catg_id = 1, description = 'Total Freight Spend by Mode ($M)', mnemonic = 'FREIGHT_SPEND', sort_order = 7, metric_data_type = 1, is_total = true;
